### ISSUE TITLE
Add support for "claim" doctype

### ISSUE THREAD

**Issue by michaelsena** [ceramicnetwork/specs#1]
The Ceramic protocol currently only supports doctypes for `3id`, `account-link`, and `policy`.

It would be great if Ceramic added support for a `claim` doctype. This would enable the protocol to support the creation of verifiable claims, which are a useful general purpose functionality that allow one or more parties to make statements about a 3ID.

It would look like: `/ceramic/claim/<CID of genesis object>`

There are potentially many ways to design the rules for this doctype, and would be interested in gathering community input on how this could be best implemented.

**Comment by gvelez-postmates** [comment]
This looks like a good idea, I think it would need some ability to link to reasons (possibly not within ceramic?), and ideally could make assertions about any URI not only a 3ID.  

use case:  I personally witnessed some event that was recorded in a news release, and that I can verify that some published article is true (or not true).  So it may be important to make assertions about things that are outside the ceramic universe, but at least be able to verify that I am the one making the assertion.

**Comment by oed** [comment]
> but at least be able to verify that I am the one making the assertion.

This can already be achieved with the `tile` doctype! Agree that it's a very good use case :)
