### ISSUE TITLE
Define document records as JSON LD documents

### ISSUE THREAD

**Issue by ukstv** [ceramicnetwork/specs#27]
**Overview**

Currently, documents are informally defined, that is only as human-comprehendible thing. It might be beneficial to reformat document definition as JSON LD with proper schema.

**Benefits**

It would bring more clarity into semantics of what is stored inside the document. Makes parsing/creation of the documents easier through existing json-ld tools.

**Comment by oed** [comment]
I think it is a good idea to use JSON-LD as a way to represent the final document that you reduce from the document log. This would allow us to take advantage of all the work that has gone into JSON-LD so far!

Document records will be signed using JWS in particular we are working on a `dag-jose` codec for IPLD. I see the records as being more internal representation used by the protocol and not something that is exposed in the same way as JSON-LD would be in the resulting document content.
