### ISSUE TITLE
Separate Patch and Content overwrite

### ISSUE THREAD

**Issue by ukstv** [ceramicnetwork/specs#30]
This is a suggestion to think on how to treat signed records content field.

Currently `content` field in signed record is defined as a patch to the previous content. Proposal is to specify that a signed record could contain either `content` or `patch`. `content` overwrites the previous document content, while `patch` contains proper patch.

Reason: it might be me, but it feels like naming different things with the same name is misleading.

**Comment by oed** [comment]
Yeah this is a good point. I do feel like there should be only one property. The reason for this is that the protocol should not care about what's in there and it should be up to the doctype to interpret the content of this property however it wants. Maybe a name like `data` is more appropriate?

**Comment by ukstv** [comment]
Maybe `content` (or even `patch`) should not ever be mentioned in the high level document definition then? The _only one property_ is `doctype`, and everything else is doctype-specific.

**Comment by oed** [comment]
Ok, in that case the required fields would be `doctype` and `owners` on the genesis record, and `prev` and `id` on subsequent records.

**Comment by sylar217** [comment]
+1 on this, as I faced similar problem when implementing verifiable credential doctype. One basic question though: Are record types(genesis, anchor and signed) something that ceramic network customers should understand or should it be kept hidden from external facing, and we should only expose customer facing fields, like doctype, owners and content. Any change is upto the doctype handler.
