### ISSUE TITLE
Layer 2 Anchor Services 

### ISSUE THREAD

**Issue by Iziren** [ceramicnetwork/specs#32]
A transitional style implementation of LND for anchoring in order to speed up the update process and potentially open the protocol to use cases with real-time anchoring needs

**Comment by oed** [comment]
Sounds interesting @Iziren Can you provide some more information about how this could work?

**Comment by Iziren** [comment]
@oed The initial thought process was that an anchor was needed in order to finalize a document update. I have since learnt that it may not necessarily be the case.

 use cases that require a more frequent update may still see a need for this approach from a cost perspective. 

I'm thinking of a google doc-like app or a forum site with multiple updates and comments.


1. A bidirectional channel can be set up between multiple CIDs on two or more blockchains
2. Both actors can carry out transactions as often as possible and choose when to place an anchor on the blockchain

This can potentially save gas costs in the long run.
