### ISSUE TITLE
Create EIP for DID provider

### ISSUE THREAD

**Issue by oed** [ceramicnetwork/specs#7]
Currently all ethereum (and other blockchain) wallets are mainly accessed though a json-rpc. Ethereum wallets have a set of methods that can be called in this way in order to sign data. In order for DIDs to create different types of claims they need to be able to sign JOSE and COSE objects. For this reason a DID provider specification should be proposed. Initially this will be an EIP but should also be reviewed by the Decentralized Identity Foundation (DIF) community, with the aim for it to become a standard for all blockchain wallets. 

## API
A rough sketch of how the methods would work. It likely also would make sense to introduce methods for doing multiple signatures/encryption/decryption operations at once.

**Signing:**

`did_sign`

- payload
- opts.format = JWS | JWT | CWS | CWT

Returns a signed object

**Signing Claim:**

`did_signClaim`

Returns a signed verifiable claim

**Encryption:**

`did_encrypt`

- payload
- opts.format = JWE | CWE

**Decryption**

`did_decrypt`

- cipher = JWE | CWE

**Comment by pedrouid** [comment]
LGTM let's add some examples to each method to make it clearer
